maps/cs_rio.bsp
maps/cs_rio.txt
maps/cs_rio.res
sound/ambience/cv.wav
sound/ambience/bezerra.wav
sound/ambience/rua1.wav
sound/ambience/rua3.wav
sound/ambience/novela.wav
sound/misc/apito.wav
sound/misc/apito2.wav
sprites/zbeam6.spr
gfx/env/riolf.tga
gfx/env/riodn.tga
gfx/env/rioft.tga
gfx/env/riobk.tga
gfx/env/riort.tga
gfx/env/rioup.tga
overviews/cs_rio.bmp
overviews/cs_rio.txt
RIODME.txt
